CREATE TABLE empresa(
    id BIGSERIAL PRIMARY KEY,
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    razao_social VARCHAR(100) NOT NULL,
    nome_fantasia VARCHAR(100) NOT NULL,
    inscricao_estadual VARCHAR(14) NOT NULL,
    inscricao_municipal VARCHAR(11) NOT NULL,
    sigla VARCHAR(10),
    logradouro VARCHAR(100) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(100),
    bairro VARCHAR(100) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    telefone VARCHAR(15),
    email VARCHAR(100) UNIQUE,
    whatsapp VARCHAR(15),
    site VARCHAR(100),
    ativo BOOLEAN NOT NULL,
    senha VARCHAR(100) NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE
)